package com.example.animatedkeyboard.audio

import android.content.Context
import android.media.AudioAttributes
import android.media.AudioFormat
import android.media.AudioManager
import android.media.AudioTrack
import android.util.Log
import com.example.animatedkeyboard.settings.KeyboardSettings
import kotlin.math.sin

/**
 * KeySoundEngine — plays a short click sound on key press.
 *
 * WHY A PROCEDURALLY GENERATED TONE (not a bundled audio file):
 * Rather than requiring an external sound asset (which would need sourcing a
 * royalty-free/non-copyrighted sample, with licensing uncertainty), this engine
 * SYNTHESIZES the click sound mathematically at runtime using a short sine-wave
 * burst with an exponential decay envelope. Because the waveform is generated by
 * code rather than recorded or copied from any existing source, there is zero
 * copyright concern — the "sound" is original output of simple arithmetic, the
 * same way a synthesizer generates notes.
 *
 * WHY AudioTrack (not SoundPool/MediaPlayer):
 * AudioTrack lets us write raw PCM samples directly, which is exactly what a
 * generated waveform is. It still plays with very low latency, suitable for
 * per-keystroke feedback.
 *
 * The generated tone itself is cached as a short PCM buffer after first build,
 * so repeated key presses are cheap (no re-synthesis per keystroke).
 */
class KeySoundEngine(private val context: Context) {

    private val settings by lazy { KeyboardSettings.getInstance(context) }
    private val sampleRate = 44100
    private var cachedClickBuffer: ShortArray? = null

    /**
     * Builds a short (~18ms) percussive "tick" tone:
     * a 1800Hz sine wave with a fast exponential amplitude decay, similar in
     * character to standard keyboard click sounds but entirely synthesized.
     */
    private fun buildClickBuffer(): ShortArray {
        cachedClickBuffer?.let { return it }

        val durationMs = 18
        val numSamples = (sampleRate * durationMs / 1000.0).toInt()
        val freqHz = 1800.0
        val buffer = ShortArray(numSamples)

        for (i in 0 until numSamples) {
            val t = i.toDouble() / sampleRate
            // Exponential decay envelope so the tone feels like a percussive "tick"
            // rather than a sustained beep.
            val envelope = Math.exp(-t * 90.0)
            val sample = sin(2.0 * Math.PI * freqHz * t) * envelope
            buffer[i] = (sample * Short.MAX_VALUE * 0.5).toInt().toShort()
        }

        cachedClickBuffer = buffer
        return buffer
    }

    /**
     * Plays the synthesized click sound if sound is enabled in settings.
     * Safe to call on every key press — building/playing a tiny PCM buffer is
     * cheap, and the buffer itself is cached after the first call.
     */
    fun playClick() {
        if (!settings.soundEnabled) return

        try {
            val buffer = buildClickBuffer()

            val attributes = AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_ASSISTANCE_SONIFICATION)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build()

            val format = AudioFormat.Builder()
                .setEncoding(AudioFormat.ENCODING_PCM_16BIT)
                .setSampleRate(sampleRate)
                .setChannelMask(AudioFormat.CHANNEL_OUT_MONO)
                .build()

            val bufferSizeBytes = buffer.size * 2 // 16-bit = 2 bytes per sample

            val track = AudioTrack.Builder()
                .setAudioAttributes(attributes)
                .setAudioFormat(format)
                .setBufferSizeInBytes(bufferSizeBytes)
                .setTransferMode(AudioTrack.MODE_STATIC)
                .build()

            track.write(buffer, 0, buffer.size)
            track.play()

            // Release the AudioTrack once playback finishes. A short-lived
            // background-safe cleanup; avoids leaking one AudioTrack per keypress.
            track.setNotificationMarkerPosition(buffer.size - 1)
            track.setPlaybackPositionUpdateListener(object : AudioTrack.OnPlaybackPositionUpdateListener {
                override fun onMarkerReached(t: AudioTrack?) {
                    try {
                        t?.stop()
                        t?.release()
                    } catch (e: Exception) {
                        Log.w(TAG, "AudioTrack cleanup failed: ${e.message}")
                    }
                }
                override fun onPeriodicNotification(t: AudioTrack?) {}
            })
        } catch (e: Exception) {
            // Non-fatal: a single missed click sound should never disrupt typing.
            Log.w(TAG, "playClick failed: ${e.message}")
        }
    }

    /**
     * No persistent native resources are held between calls (each AudioTrack is
     * short-lived and self-releases via the marker listener above), so release()
     * only needs to clear the cached buffer. Kept as a no-op-safe method so the
     * call site in KeyboardView/IME doesn't need to change.
     */
    fun release() {
        cachedClickBuffer = null
    }

    companion object {
        private const val TAG = "KeySoundEngine"
    }
}
